#!/bin/sh
if ! head -1 "$1" | grep -qE "^(<type>feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)\((<scope>global|signifier|authentifier)\)?: .{1,}$"; then
    echo "aborted: Your commit message doesn't respect conventional commit syntax" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "aborted: Your commit message is too long." >&2
    exit 1
fi
